# Generated by Django 2.2 on 2020-07-05 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemId', models.CharField(max_length=100, unique=True)),
                ('itemName', models.CharField(max_length=100)),
                ('itemPrice', models.FloatField()),
                ('itemStock', models.IntegerField()),
                ('pIMG1', models.ImageField(upload_to='productinfo')),
                ('pIMG2', models.ImageField(upload_to='productinfo')),
                ('pIMG3', models.ImageField(upload_to='productinfo')),
            ],
        ),
    ]
